### ISSUE TITLE
Everything Wrong with Quillyjumper

### ISSUE THREAD

**Issue by DRSchlaubi** [Quillraven/Quilly-s-Adventure#11]
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/build.gradle.kts#L1
Build script DSL is obsolete using plugins DSL is recommended `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/build.gradle.kts#L3
You don't use any plugin from maven local `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/build.gradle.kts#L4
This is unnecessary this it's getting proxied by JCenter `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/build.gradle.kts#L5
This is the default repo afaik `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/build.gradle.kts#L6
Should be proxied by JCenter but you don't use it anyways `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/build.gradle.kts#L20-L26
Everything above applies to this as well `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/desktop/build.gradle.kts#L28
Why the hell is the assets folder in the android directory these don't seem to be Android only assets `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/buildSrc/src/main/java/Dependencies.kt#L1-L20
`.kt` file in `java` folder `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/android/AndroidManifest.xml#L3
Quillraven PRESENTS THE ONE AND ONLY `gamename` `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/android/src/com/game/quillyjumper/AndroidLauncher.kt#L8
Something is telling me that this is not nullable `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/build.gradle.kts#L33
Java 7 reached it's EOL in 2014 or something `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/master/core/src/main/kotlin/com/game/quillyjumper/trigger/Map2Trigger.kt
That's not how you name Kotlinfiles properly `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/trigger/Map2Trigger.kt#L28
Use of println even if there is a logger in the classpath `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/trigger/Map2Trigger.kt#L65-L66
You don't use these shortenings in Java or Kotlin (I am not going to link every occurrence of this since I want to do other things this year) `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/trigger/Trigger.kt#L23-L29
Oneliners that aren't actual Kotlin oneliners `(+1)` 
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/screen/EndScreen.kt#L10
the logging thing again `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/screen/GameScreen.kt#L175-L256
NAMING FTW `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/screen/LoadingScreen.kt#L35
```Kotlin
 MusicAssets.values().forEach(assets::load)
``` 
`(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/screen/LoadingScreen.kt#L37
```Kotlin
        TextureAtlasAssets.values().forEach(assets::load)
```
`(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/screen/LoadingScreen.kt#L38
```Kotlin
        MapAssets.values().forEach(assets::load)
```
`(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/screen/LoadingScreen.kt#L44-L46
One liner that is not actually a one-liner `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/screen/MenuScreen.kt#L39-L45
Oneliners that aren't actual oneliners `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/input/InputListener.kt#L6
I am not a native speaker but I think it's called percent `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/EcsUtils.kt#L602
Find method does not return the thing that it is supposed to find `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/EcsUtils.kt#L574-L580
Kotlin reflect is made for "reflecting" Kotlin `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/EcsUtils.kt#L567
Naming `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/EcsUtils.kt#L472
Unnecessary `this` is unnecessary (also in  L490, L472, 439, 384, 359, 333, 233, 83, 55, 58, 70 and 43)
https://rice.by.devs-from.asia/idea64_HWngFn0yw9.png
These are way too many files I would combine all of these 10 lines long classes into one file (or categorize them and put one category in one file `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/system/RenderPhysicDebugSystem.kt#L18-L20
Fake oneliner `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/system/RemoveSystem.kt#L25-L27
Make the Listener abstract and don't override if not wanting to do anything THX `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/system/RemoveSystem.kt#L36-L38
Fake oneliner again `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/system/PhysicJumpSystem.kt#L24
This should be an if `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/system/ParticleSystem.kt#L54
What is that even supposed to mean? Is the Runescape username of your girlfriend? `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/system/ParticleSystem.kt#L63-L65
`AudioService#play()` should check that `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/system/OutOfBoundsSystem.kt#L80-L82
Fake one-liner `(+1)`
https://rice.by.devs-from.asia/chrome_T1DTlVCjQU.png
Chrome wants do die right now and I can understand little Chrome `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/component/TriggerComponent.kt#L14-L16
Companion objects are supposed to be at the very bottom of class `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/component/TransformComponent.kt#L26-L28
Yeah the same thing again (won't repeat me for the rest of `component` `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/component/TransformComponent.kt#L21-L24 
this could be an operator fun but it probably won't help much `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/ecs/component/TakeDamageComponent.kt#L16-L18
Last time that I am going to point out fake oneliners I think you got it `(+1)`
https://rice.by.devs-from.asia/chrome_9vl8QDoBy2.png
Somehow GitHub fails syntax highlighting this  
https://github.com/Quillraven/QuillyJumper/blob/master/core/src/main/kotlin/com/game/quillyjumper/ecs/component/AttackComponent.kt `(+1)`

Not pointing out fake oneliners and companion objects anymore saved me a lot of time `(+1)`

https://github.com/Quillraven/QuillyJumper/tree/master/core/src/main/kotlin/com/game/quillyjumper/configuration
This thing actually isn't that bad `(-1)`
https://github.com/Quillraven/QuillyJumper/blob/aad2db5f9f94eb28f789785ac5cb65e8f06237db/core/src/main/kotlin/com/game/quillyjumper/audio/DefaultAudioService.kt#L20
Why not using `kotlin.collections` it's way better `(+1)`
https://github.com/Quillraven/QuillyJumper/blob/master/core/src/main/kotlin/com/game/quillyjumper/assets/Assets.kt
Those enums should each have a folder name constant as every enum constant is in the same folder `(+1)`
I actually had to remove the Android project to make this project compile `(+1)`
Cause this project has no `.idea` folder I had to set up all of the settings again `(+1)`
It takes to long to generate all of the project files (Just importing the build.gradle.kts and that's it) `(+1)`
There is no license header `(+1)`
Each submodule has it's own build folder `(+1)`
I am not mentioned in the `LICENSE` file neither am I in the credits.txt `(+1)`

There are a whole bunch of other issues but most of them were already mentioned and I don't want to spent another week in writing all of them down

Issues: `48`

**Comment by Quillraven** [comment]
- changed buildscript to plugin DSL
- removed unnecessary repositories (snapshot is needed for libktx at the moment)
- assets folder moved to root project
- buildSrc src file got moved to kotlin folder
- fixed packagename in AndroidManifest.xml

other things will not be changed as they are not important and don't add anything to the project.

Also, Kotlin collections are not better than libgdx ones because iteration will always create a new iterator instance which triggers the GC more often. LibGDX takes care of that and reuses the iterator. This is especially important for android development.

**Comment by DRSchlaubi** [comment]
> Also, Kotlin collections are not better than libgdx ones because iteration will always create a new iterator instance which triggers the GC more often. LibGDX takes care of that and reuses the iterator. This is especially important for android development. #

That's what sequences are for they should not create an iterator every time and also both the Java GC and phone hardware improved since the release of Java 7
