### ISSUE TITLE
Add detekt to detec(k)t Kotlin code style

### ISSUE THREAD

**Issue by DRSchlaubi** [Quillraven/Quilly-s-Adventure#13]
Use this cool tool to detekt code quality: https://github.com/arturbosch/detekt
Would assign that to me but I am no longer a collaborator

**Comment by Quillraven** [comment]
Commit 5df6df5bb02f70c44d190bd9781637789787873f adds detekt with some sensible configuration for the project.

Thanks for the help yesterday, to show how to include it and set it up.

Now it would be great if github does the check automatically (Travis? ;))

**Comment by DRSchlaubi** [comment]
Stopp with the Travis thing I told you to use GitHub actions several times
