### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by DRSchlaubi** [Quillraven/Quilly-s-Adventure#14]
Add GitHub actions to verify code quality on PRs and create artifacts

**Comment by Quillraven** [comment]
Added some first github actions but they don't work yet properly. What we need:
- when pushing to the project the run gradle clean, build and detekt to verify that the code base is working
- once the first job (mentioned in the step above) was successful, another action should automatically create a SNAPSHOT release and adding the desktop jar to it, which is build via gradle shadowJar task
- once all of that is working then we can also add badges to the README.md to visualize if the current repository is building correctly

**Comment by Quillraven** [comment]
@DRSchlaubi I was able to create a workflow that seems to build, run detekt, create jar, create release and attach shadowJar to release.

refer to https://github.com/Quillraven/Quilly-s-Adventure/blob/master/.github/workflows/master.yml

However, this workflow cannot update the release. Could you please help with that? I think the other workflows are then not needed?

**Comment by DRSchlaubi** [comment]
If someone PRs just to core/ you do not want to run the desktop and Android workflows on that or that's why there a separate worlflows

**Comment by Quillraven** [comment]
Agree that if android project changes that the desktop jar build process does not need to run.
But core/desktop are tied together in my opinion and should be able to always produce a runnable jar

**Comment by Quillraven** [comment]
Thanks for the help @DRSchlaubi. I think we can close this issue for now. The way it works at the moment:
- push to master disabled
- pull requests that change desktop/core will trigger a workflow that runs build, detekt and builds the jar
- pull request must be approved by at least one reviewer
