### ISSUE TITLE
LibKTX showcase

### ISSUE THREAD

**Issue by czyzby** [Quillraven/Quilly-s-Adventure#20]
Is it OK if I add your project to the LibKTX showcase on the official website? You're using a significant portion of LibKTX APIs - I think this project would be a useful resource for people starting with the framework.

**Comment by Quillraven** [comment]
Sure, feel free to add it if you think it is useful.

Now you know where the root of my created issues for libktx came from haha.

**Comment by czyzby** [comment]
> Now you know where the root of my created issues for libktx came from haha.

Contributions like that are the best, because you know they solve actual problems.

Anyway, this is a very nice project. Looking forward to the release. :)

**Comment by Quillraven** [comment]
Thanks! Then feel free to link it :) Glad when I can help
