### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by Tarek-Hasan** [Quillraven/Quilly-s-Adventure#46]
I was searching for open source platformer games, when I came across this project. While interesting and promising, development of the project seems stopped. If you are willing to continue the development, here are some cool open resources you can use to improve the game.
[Duelyst](https://github.com/open-duelyst/duelyst) - everything is licensed under CC0.
[Frogatto & Friends](https://github.com/frogatto/frogatto) - everything is licensed under CC-BY 3.0, except for a few specific directories.
   The following directories and all of their contents are copyrighted to the frogatto team.
   - data/levels, which contains all level files
   - images/characters, which contains all of main-character art
   - images/tiles, which contains tile art
   - sounds, which contains sound effects
   - music, which contains background music

I hope you will look into these projects.

**Comment by Quillraven** [comment]
This was a twitch streaming project a few years ago and the goal was achieved to have a jump&run adventure RPG like game ;)

It is open source, so everyone is free to continue this project or adapt it. I don't have any motivation or time at the moment to work on this game but who knows - maybe one day I will continue the story ;)
